### ISSUE TITLE
KeePassHttp plugin dependencies list fix for deb package

### ISSUE THREAD

**Issue by synchrone** [dlech/keepasshttp#1]
`keepass2-plugin-keepasshttp` does not have any dependencies.

The correct list of dependencies looks like: 

```
libmono-system-xml-linq4.0-cil
libmono-system-data-datasetextensions4.0-cil
libmono-system-runtime-serialization4.0-cil
```

It can also work as a *.plgx file, windows-like, if `mono-mcs` wold be installed, but I see no reason to do that.

Also, the package bundles `
/usr/lib/keepass2/plugins/keepasshttp/Newtonsoft.Json.dll` file, which is wrong since it's available as a GAC binary via `libnewtonsoft-json5.0-cil`

**Comment by dlech** [comment]
What OS/version are you running?

**Comment by synchrone** [comment]
These packages are present in debian jessie, and hence ubuntu trusty, which I used to test the package building.

**Comment by dlech** [comment]
Thanks for the pull request. I ended up fixing it using `${cli:Depends}` instead of explicit specifying the depends. I've published this to `ppa:dlech/keepass2-plugins-beta`.  If you confirm that it works, I'll move it over to `ppa:dlech/keepass2-plugins`.

**Comment by synchrone** [comment]
Okay,
`libmono-system-xml-linq4.0-cil` is a dependency of newtonsoft.json, so keepass don't need to depend on it explicitly.
Same goes for `libmono-system-data-datasetextensions4.0-cil` and `libmono-system-runtime-serialization4.0-cil`.

However, the beta-channel package seems to depend on `libmono-winforms2.0-cil (>= 2.4)`, which is wrong, because keepass2 already depends on `libmono-system-windows-forms4.0-cil`.

Now, I am not exactly familiar with how `dh_makeclilibs` discovers them package names based on *.dll imports, so could you please check if the DLL is indeed built not being dependant on v2.0 CLR? I mean it would of course work with v4 due to backwards-compatibility, but keepass2 is already built for v4.0 so there's no sense depending on a lower version, and we'd have less dependencies installed.

**Comment by dlech** [comment]
I've updated the package to build using .NET 4.0 instead of .NET 2.0. It now depends on 

```
libmono-corlib4.5-cil (>= 3.2.8)
libmono-system-core4.0-cil (>= 3.2.8)
libmono-system-drawing4.0-cil (>= 3.0.6)
libmono-system-windows-forms4.0-cil (>= 1.0)
libmono-system4.0-cil (>= 3.2.8)
libnewtonsoft-json5.0-cil (>= 5.0r6)
keepass2 (>= 2.17)
```

Some of these are redundant because they are dependencies of `keepass2`. This is because of

```
dh_clideps: Warning: No Debian dependency data for KeePass (2.25.0.41652__0738eb9f132ed756)!
```

So really the problem causing the redundant dependencies is in the `keepass2` package. It's not really hurting anything though, so I'm OK with leaving it that way for now.

**Comment by synchrone** [comment]
Yeah, this works fine :+1:
